spring.application.name=SoleVault

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
logging.level.org.springframework.jdbc.core.simple.JdbcClient=DEBUG

# Validation messages
spring.messages.basename=ValidationMessages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=3600

# H2 in-memory baza
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.sql.init.schema-locations=classpath:schema.sql
#spring.datasource.sql.init.data-locations=classpath:data.sql

# JPA
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# H2 konzola (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true

# Inicijalni podaci
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

# Security
jwt.token-validity-seconds=86400
jwt.base64-secret=c29sZVZhdWx0U2VjcmV0S2V5Rm9ySldUQXV0aGVudGljYXRpb24hMjAyNg==
security.bcrypt-strength=12

# CORS
app.cors.allowed-origins=http://localhost:5173
app.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
