CREATE TABLE IF NOT EXISTS brand (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    country     VARCHAR(50) NOT NULL,
    founded     DATE NOT NULL DEFAULT CURRENT_DATE CHECK (founded <= CURRENT_DATE),
    logo_url    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS sneaker (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model           VARCHAR(255) NOT NULL,
    brand_id        BIGINT NOT NULL,
    size            DECIMAL(4,2) NOT NULL CHECK (size >= 35 AND size <= 50),
    colorway        VARCHAR(64) NOT NULL,
    buy_price        DECIMAL(10,2) NOT NULL,
    current_value    DECIMAL(10,2) NOT NULL,
    condition       ENUM('NEW', 'USED') NOT NULL DEFAULT 'NEW',
    purchased_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (brand_id) REFERENCES brand(id)
);