CREATE TABLE IF NOT EXISTS brand (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    country     VARCHAR(50) NOT NULL,
    founded     DATE NOT NULL DEFAULT CURRENT_DATE CHECK (founded <= CURRENT_DATE),
    logo_url    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS sneaker (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model           VARCHAR(255) NOT NULL,
    brand_id        BIGINT NOT NULL,
    size            DECIMAL(4,2) NOT NULL CHECK (size >= 35 AND size <= 50),
    colorway        VARCHAR(64) NOT NULL,
    buy_price       DECIMAL(10,2) NOT NULL,
    current_value   DECIMAL(10,2) NOT NULL,
    condition       ENUM('NEW', 'USED') NOT NULL DEFAULT 'NEW',
    purchased_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (brand_id) REFERENCES brand(id)
);

CREATE TABLE IF NOT EXISTS price_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sneaker_id  BIGINT,
    price       DECIMAL(10,2),
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    source      VARCHAR(100),
    FOREIGN KEY (sneaker_id) REFERENCES sneaker(id)
);

CREATE TABLE IF NOT EXISTS want_list_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model           VARCHAR(255) NOT NULL,
    brand           VARCHAR(255) NOT NULL,
    target_price    DECIMAL(10,2) NOT NULL,
    added_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes           VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS sneaker_image (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url         VARCHAR(255) NOT NULL,
    tag         VARCHAR(55),
    description VARCHAR(255),
    sneaker_id  BIGINT NOT NULL,
    FOREIGN KEY (sneaker_id) REFERENCES sneaker(id)
);

CREATE TABLE IF NOT EXISTS "user" (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS authority (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_authority (
    user_id         BIGINT NOT NULL,
    authority_id    BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "user"(id),
    FOREIGN KEY (authority_id) REFERENCES authority(id)
);
